######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 30 18:02:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug src ui
INCLUDEPATH += .

# Input
HEADERS += src/com.h src/plotter.h
FORMS += ui/wirelessglove.ui
SOURCES += src/com.cpp src/main.cpp src/plotter.cpp
RESOURCES += plotterplugin.qrc
